name: screen_brightness_macos
description: The macOS federated plugin implementation of the screen_brightness.
version: 0.0.1-dev.2
homepage: https://github.com/aaassseee/screen_brightness
repository: https://github.com/aaassseee/screen_brightness/tree/feature/macos_support/screen_brightness_macos
issue_tracker: https://github.com/aaassseee/screen_brightness/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
#  screen_brightness_platform_interface:
#    path: ../screen_brightness_platform_interface/
  screen_brightness_platform_interface: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ScreenBrightnessMacosPlugin
